SET SERVEROUTPUT ON;
DECLARE

    SEXO CHAR(1) := 'F';
    
BEGIN

    IF SEXO = 'M' OR SEXO = 'm' THEN
        DBMS_OUTPUT.PUT_LINE('PESSOA DO SEXO MASCULINO');
    ELSIF SEXO = 'F' OR SEXO = 'f' THEN
        DBMS_OUTPUT.PUT_LINE('PESSOA DO SEXO FEMININO');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('OUTROS');
    END IF;

END;
